# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_api: AIzaSyCIuBbNIuqH42xNtzIDdrnLR5hPdZF2QCI
  secret_key_base: b48ce81644af4ac8471cd12644acc668e973c6f42d603cf5a0fefa8fde4e78ca7fbcd8fb8d3b0ab97eec1c2a9f43ec579f1d2bac9857aac1727f4f5dd92cd486
  

test:
  secret_key_base: 3132eaf96ead659884fb2a14dfb307b0c66767081b9df3d20757fa7ae1fd1e0bfcea452a3c8b6f7b681c999b81931c53d499a318993ee8fe188eafd98652b06c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_api: <%= ENV["GOOGLE_API"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
